compiler = "gyc"
license = "GPL-v3"
name = "midgard"
description = "Ymir runtime and std library"
authors = ["Emile Cadorel <ecadorel@gmail.com>"]
version = "1.3.6"

[targets.gymidgard_release]
type = "library"
libraries = []
description = ""
name = "gymidard_release"
package-root = "__lib__"
source-dir = "midgard"
flags = ["-fPIC", "-nostdinc", "-nomidgardlib"]
c-sources = ["rt/**/*.c"]
c-flags = ["-I."]
tests = false

[targets.gymidgard_debug]
type = "library"
libraries = []
description = ""
name = "gymidard_debug"
package-root = "__lib__"
source-dir = "midgard"
flags = ["-fPIC", "-nostdinc", "-nomidgardlib", "-fversion=DEBUG_LIB", "-g"]
c-sources = ["rt/**/*.c"]
c-flags = ["-I."]
tests = false

[targets.gymidgard_tests]
type = "library"
libraries = []
description = ""
name = "gymidard_tests"
package-root = "__lib__"
source-dir = "test-rt"
flags = ["-fPIC", "-nostdinc", "-nomidgardlib", "-fversion=DEBUG_LIB", "-g", "-I./midgard/"]
c-sources = ["test-rt/**/*.c"]
c-flags = ["-I."]
tests = false

[targets.gymidgard_debug_unit]
type = "library"
libraries = []
description = ""
name = "gymidard_debug"
package-root = "__lib__"
source-dir = "midgard"
flags = ["-fPIC", "-nostdinc", "-nomidgardlib", "-fversion=DEBUG_LIB", "-g", "-funittest"]
c-sources = ["rt/**/*.c"]
c-flags = ["-I."]
tests = false

[targets.midgard_tests]
type = "executable"
libraries = ["gc", "pthread", "dwarf", "m"]
description = ""
name = "midgard_tests"
package-root = "__lib__"
source-dir = "tests"
flags = ["-fPIC", "-nostdinc", "-nomidgardlib", "-fversion=DEBUG_LIB", "-g", "-funittest"]
targets = ["gymidgard_debug_unit", "gymidgard_tests"]
tests = false

[dependencies]

[registry]
git = "git@github.com:GNU-Ymir/yruntime.git"

