license = "GPL-v3"
author = "Emile Cadorel <ecadorel@gmail.com>"
libraries = []
type = "library"
description = "Ymir bootstrap compiler"
version = "0.1.0"
name = "midgard"

[dependencies]

[registry]
git = "git@github.com:GNU-Ymir/yruntime.git"