name: Bump patch version

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump_patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/bump-version
        with:
          part: patch
